#!/bin/bash

# List of YouTube URLs
urls=(
  "https://www.youtube.com/watch?v=po6kjouyxXg"
  "https://www.youtube.com/watch?v=dyEdcOhxJNQ"
  "https://www.youtube.com/watch?v=lbfWsIpXsCA"
  "https://www.youtube.com/watch?v=kBKA3g8WTuE"
  "https://www.youtube.com/watch?v=SlHIRkgpD24"
  "https://www.youtube.com/watch?v=OSpbQc4DZCA"
  "https://www.youtube.com/watch?v=AMuRRXCuy-4"
  "https://www.youtube.com/watch?v=VyqhPYe0vew"
  "https://www.youtube.com/watch?v=yIzCBU0_LyY"
  "https://www.youtube.com/watch?v=FFbc-jXkADs"
  "https://www.youtube.com/watch?v=XxrEISBLhY0"
  "https://www.youtube.com/watch?v=kEUXdnyXXO0"
  "https://www.youtube.com/watch?v=aPVvXlnV3Vg"
  "https://www.youtube.com/watch?v=xobeTscjOM0"
  "https://www.youtube.com/watch?v=mZRJfQluJTM"
  "https://www.youtube.com/watch?v=cHLgOcsngTI"
  "https://www.youtube.com/watch?v=ptqkTdtt7nI"
  "https://www.youtube.com/watch?v=v_nkcw1mD_8"
  "https://www.youtube.com/watch?v=Wy6ec9YTO8g"
  "https://www.youtube.com/watch?v=9dcBy2uXL7E"
  "https://www.youtube.com/watch?v=GigepCcpWas"
  "https://www.youtube.com/watch?v=H7Y5a7Y-jng"
  "https://www.youtube.com/watch?v=6db52BxXxfQ"
  "https://www.youtube.com/watch?v=tSjrsT8pTbQ"
  "https://www.youtube.com/watch?v=lfJKW2lmQTQ"
  "https://www.youtube.com/watch?v=56I2rxRPRLY"
  "https://www.youtube.com/watch?v=XRuqrlBmzAY"
  "https://www.youtube.com/watch?v=j7TM2ccOGbU"
  "https://www.youtube.com/watch?v=wzYGh5-2sc4"
  "https://www.youtube.com/watch?v=eVnG_Rqfgg4"
  "https://www.youtube.com/watch?v=xwuzVSUnEgI"
  "https://www.youtube.com/watch?v=ieE4ygt9kfc"
  "https://www.youtube.com/watch?v=BXaqBNTl7zI"
  "https://www.youtube.com/watch?v=9Ie-Y8JL5t4"
  "https://www.youtube.com/watch?v=eHxK5L_kvzg"
  "https://www.youtube.com/watch?v=SbFT9nYDRBo"
  "https://www.youtube.com/watch?v=xPl-cM2dDj0"
  "https://www.youtube.com/watch?v=0AwkZihdw6E"
  "https://www.youtube.com/watch?v=cTvUrpSr9ck"
  "https://www.youtube.com/watch?v=dDfx5xM7yno"
  "https://www.youtube.com/watch?v=2ODQEjSUnok"
  "https://www.youtube.com/watch?v=YQNb89xnKvQ"
  "https://www.youtube.com/watch?v=vHGHzYFzr-E"
  "https://www.youtube.com/watch?v=wtfRQ76-I7k"
  "https://www.youtube.com/watch?v=UBgAsQrlpqc"
  "https://www.youtube.com/watch?v=no0cwOYvinI"
  "https://www.youtube.com/watch?v=BOLYNw3x1lE"
  "https://www.youtube.com/watch?v=I81r9C5Mk14"
  "https://www.youtube.com/watch?v=kR8rsh1AqRs"
  "https://www.youtube.com/watch?v=9XOnMlK5WBY"
  "https://www.youtube.com/watch?v=lNW8qsoeWs4"
  "https://www.youtube.com/watch?v=EVmbe3TfyeM"
  "https://www.youtube.com/watch?v=yFuiswpYeV0"
  "https://www.youtube.com/watch?v=4hM6MqHZw9U"
  "https://www.youtube.com/watch?v=vjmOomq2x2A"
  "https://www.youtube.com/watch?v=Ewj3fShfZow"
  "https://www.youtube.com/watch?v=IsKN8iylATk"
  "https://www.youtube.com/watch?v=FKRdfz466wE"
  "https://www.youtube.com/watch?v=qgsbn8IoUqc"
  "https://www.youtube.com/watch?v=OkhjzAfaH0I"
  "https://www.youtube.com/watch?v=h34dmUw_yCQ"
  "https://www.youtube.com/watch?v=MDXFi3avqo0"
  "https://www.youtube.com/watch?v=ztLjAiErnFc"
  "https://www.youtube.com/watch?v=OybNT11fIvg"
  "https://www.youtube.com/watch?v=60LJ1HqNwKM"
  "https://www.youtube.com/watch?v=cBqq_3d_tO0"
  "https://www.youtube.com/watch?v=ofkL9rbUMEk"
  "https://www.youtube.com/watch?v=zuHsssMfKIQ"
  "https://www.youtube.com/watch?v=H8Uc7nWSQBo"
  "https://www.youtube.com/watch?v=5z5724Cc9Jg"
  "https://www.youtube.com/watch?v=GBfvn7QMA_c"
  "https://www.youtube.com/watch?v=a7yWDs_XmEo"
  "https://www.youtube.com/watch?v=17AXtxleQZk"
  "https://www.youtube.com/watch?v=TqdNqBA44Bg"
  "https://www.youtube.com/watch?v=vmDWt1skq24"
)

# Loop through the URLs and download each
for url in "${urls[@]}"; do
  # Get the song title without downloading, to use it in the message
  song_name=$(yt-dlp --get-title "$url" 2>/dev/null)

  # Download audio in WAV format, suppressing yt-dlp output
  yt-dlp -x --audio-format wav -o "%(title)s.%(ext)s" "$url" >/dev/null 2>&1

  # Print the download confirmation message
  echo "Downloaded ${song_name}"
done
